---
sudo: required
dist: trusty

install:
  # Update docker-engine using Ubuntu 'trusty' apt repo
  - >
    curl -sSL "https://get.docker.com/gpg" |
     sudo -E apt-key add -
  - >
    echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" |
     sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - >
    sudo apt-get -o Dpkg::Options::="--force-confdef" \
     -o Dpkg::Options::="--force-confold" --assume-yes install docker-engine \
     --allow-unauthenticated
  - docker version
  # Update docker-compose via pip
  - sudo pip install docker-compose
  - docker-compose version

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

cache:
  directories:
    - $HOME/docker

before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi  

before_script:
  - cd docker
  - touch ./compose/.env
  - chmod +x ../travis.test.sh
  - docker-compose down  
  - docker-compose -f ./docker-compose.electron.yaml build
  - docker-compose -f ./docker-compose.electron.yaml up 
  - sudo chmod 777 -R ./compose/app/.build 
  - cp ./compose/app/.build/electron/desktop.js ./compose/app/.build/public/main.js
  - cp ./compose/app/src/package.json ./compose/app/.build/public  

script:
  - ../travis.test.sh
