version: '3.2'

services:
    node:
        stdin_open: true
        tty: true
        restart: always

        build:
            context: ./compose/app
            args:
              - START_SCRIPT=./override.export.sh
        container_name: app
        restart: always
        env_file:
            - ./compose/.env
        ports:
            - "3003:3003"
        volumes:
            - 
                type: volume
                source: ./compose/app/.build
                target: /dist
                    
