version: '3.2'

services:
    node:
        stdin_open: true
        tty: true
        restart: always

        build:
            context: ./compose/app
            args:
                - START_SCRIPT=./override.start.dev.sh
        container_name: app
        restart: always
        env_file:
            - ./compose/.env
        ports:
            - "3003:3003"
        volumes:
            - 
                type: volume
                source: ./compose/app/src
                target: /org-src                    
    nginx:
        restart: always
        build:
            context: ./compose/nginx/
            args:
                - SETUP_DOMAIN=example.com

        ports:
            - "443:443"
        links:
            - node:node
