version: '3.2'

services:
    node:
        stdin_open: true
        tty: true
        restart: always

        build:
            context: ./compose/app
        container_name: app
        restart: always
        env_file:
            - ./compose/.env
        environment:
            - PUSHFOR_VENDOR=pushfor
        ports:
            - "3003:3003"
        volumes:
            - 
                type: volume
                source: ./compose/app/src
                target: /org-src                    
        argument:
            - ARGUMENT_1=gulp watch &

